[package]
name = "learn_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
pgp = "0.18.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "mysql"] }
tokio = { version = "1.48.0", features = ["full"] }
